### ISSUE TITLE
Improve the password validation

### ISSUE THREAD

**Issue by nellfs** [openpasswd/openpasswd#8]
### ⚠️ The problem
Openpasswd doesn't have a good character validation for passwords yet. The only real validation is that the password is not empty. Actually you can use a password with just only 1 character, which makes it vulnerable.

### 
### 📙 Validation tips
1. The password length must be greater than or equal to 8
     - ☝️ This is the only one that should be mandatory
     
2. The password must contain one or more uppercase characters
3. The password must contain one or more lowercase characters
4. The password must contain one or more numeric values
5. The password must contain one or more special characters

**Comment by ricardoalcantara** [comment]
For now I will only implement the first one!
